[meta]
  title = "Node Live Text-to-Speech Starter"
  description = "Get started using Deepgram's Live Text-to-Speech with this Node demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Live TTS"
  language = "JavaScript"
  framework = "Node"

[build]
  command = "npm install"

[config]
  sample = "sample.env"
  output = ".env"

[post-build]
  message = "Run `npm run start` to get up and running."
